### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by KaiDevrim** [pridkett/ansible-role-fish#1]
Hello, how do I install this? Installing using `ansible-galaxy` does not seem to work?

**Comment by pridkett** [comment]
This repository isn't part of `ansible-galaxy`, you can use `requirements.yml` to install it.

If you haven't already, create `requirements.yml` with the following content:

```yaml
---
- name: pridkett.fish
  scm: git
  src: https://github.com/pridkett/ansible-role-fish.git
  version: master
```

Then you can still use `ansible-galaxy` to pull down the roles:

```bash
ansible-galaxy install -r requirements.yml -p roles
```

Or to update the roles:

```bash
ansible-galaxy install -f -r requirements.yml -p roles
```

That should take care of it for you.
